### ISSUE TITLE
Data is not uploaded to aprsis

### ISSUE THREAD

**Issue by dl4zaa** [9V1KG/ygate2#11]
Hello, 
I am not sure if this is the proper way to get in touch with you about the ygate2 module.
I tried to set it up on a raspberry with an FTM 100 and everything seems to work pretty nice, except there is no upload to the aprsis system. Do I miss something? 
Thank you for your support.

73 de DL4ZAA, Ralf

**Comment by 9V1KG** [comment]
Hello Ralf,
can you see the login response from the APRS server when you start the program?
Are the details correct? (Call sign and secret number?)

**Comment by dl4zaa** [comment]
Hi Klaus,

these are some lines printed on the command line:

10:23:17 [INFO] No kiss modem found
10:23:18 [INFO] # aprsc 2.1.5-g8af3cdc
10:23:18 [INFO] # logresp DL4ZAA-10 verified, server T2ERFURT
10:23:18 [POS ] DL4ZAA-10>APZ209,TCPIP*:=/4[**PpXp#C)tTesting Yaesu IGate 2.0 program - 73
10:23:18 [INFO] I/O: APRS-IS: ON APRS-IS RX: ON Serial: ON
                KISS: OFF
10:23:23 [STAT] DL4ZAA-10>APZ209,TCPIP*:>IGate is up - RF-IS for FTM-400:
                https://github.com/9V1KG/Ygate2

I can't see any problems. Would the log file help?

Ralf

**Comment by 9V1KG** [comment]
Die Daten gehen aber raus:

**Comment by dl4zaa** [comment]
Sehr seltsam.
Jetzt finde ich meinen Eintrag auf aprs.fi und aprsdirect.com, aber mit 2 Stunden Verspätung. In den Raw Daten auf den Servern sind meine aktuellen Daten zu sehen, aber sie werden nicht auf der Karte dargestellt, oder erst mit etwa 2h Verspätung.

**Comment by dl4zaa** [comment]
Nach einiger Zeit bricht das Programm immer mit den folgenden Meldungen ab:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/src/ygate2/ygate2/__main__.py", line 8, in <module>
    YGATE.main()
  File "/home/pi/src/ygate2/ygate2/ygate2.py", line 708, in main
    = select.select(self._inputs, self._outputs, [])

Vielleicht hat das etwas mit dem Problem zu tun?

**Comment by 9V1KG** [comment]
Hallo Ralf,
nein, upload zum APRS server sollte eigentlich ohne probleme laufen. Manchmal ist das APRS netzwerk langsam. Das o.a. Problem kenne ich, hab aber noch keine Loesung dafuer gefunden. Wenn du eine stabile Version suchst, die Vorgaenger Version laeuft ohne Problem, ist allerdings nicht interaktiv: https://github.com/9V1KG/Igate-n

**Comment by dl4zaa** [comment]
Hallo Klaus,
ich werde das nochmal beobachten. Zuvor hatte ich ein Raspberry APRS IGate auf Basis pymultimonaprs mit einem RTL-Stick. Da waren die Einträge umgehend auf den Karten zu sehen. Daher hatte ich erwartet, dass sich das bei ygate2 auch so verhält. 
Danke für den Tipp mit der Vorgängerversion. Vielleicht probiere ich die noch aus.
vy 73, Ralf
