### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by loopmasta** [9V1KG/ygate2#12]
```
12:08:26 [MICE] DL7PL>UQ2QV1,WIDE1-1,WIDE2-2,qAO,DL3KU-15:`}?/\x1c\x1dP-\\"6F}DL7PL-J\xfcrgen-OV
                O27- Digi Hohenlimburg

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/ygate2/ygate2/__main__.py", line 8, in <module>
    YGATE.main()
  File "/home/pi/ygate2/ygate2/ygate2.py", line 710, in main
    self._dispatch_in.get(sel)()
  File "/home/pi/ygate2/ygate2/ygate2.py", line 579, in _hdl_aprs_rx
    self.packet_parse(packet)
  File "/home/pi/ygate2/ygate2/ygate2.py", line 408, in packet_parse
    self._hdl_print(7 * " " + aprs.mic_e_decode(p_dec))
  File "/home/pi/ygate2/aprsutils/aprs_util.py", line 225, in mic_e_decode
    r"[\x1c\x1d`'][&-~,\x7f][&-a][\x1c-~,\x7f]{5,}", m_i.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 20: ordinal not in range(128)

```

**Comment by 9V1KG** [comment]
Invalid packet containing a non ASCII character.
